version: "3.9"

services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: "pomodoro"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
#    volumes:
#      - .:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"

  cache:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6380:6379'

